mysql:
    image: mysql:5.7
    ports:
        - "3306:3306"
    expose:
        - 3306
    volumes:
        - ./config/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_USER: root
        MYSQL_PASSWORD: 123456
        MYSQL_DATABASE: slimdb
php:
    build: ./config/php/
    ports:
        - "9000:9000"
    volumes:
        - ./www:/var/www
    links:
        - mysql
nginx:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php        
